# Generated by Django 2.2 on 2019-05-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keuangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('kategori', models.CharField(choices=[('REGISTRASI', 'REGISTRASI'), ('IKLAN', 'IKLAN'), ('DONASI', 'DONASI'), ('LAIN2', 'LAIN2'), ('CASH', 'CASH'), ('TRANSFER', 'TRANSFER')], max_length=10)),
                ('keterangan', models.TextField(max_length=100)),
                ('masuk', models.DecimalField(decimal_places=2, max_digits=15)),
                ('keluar', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'verbose_name': 'Keuangan',
                'verbose_name_plural': 'Keuangan',
            },
        ),
    ]
