# Generated by Django 2.2 on 2019-05-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0002_auto_20190501_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peserta',
            name='hp',
            field=models.TextField(max_length=20),
        ),
    ]
