# Generated by Django 2.2 on 2019-05-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0003_auto_20190501_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peserta',
            options={'verbose_name': 'Peserta Seminar', 'verbose_name_plural': 'Peserta Seminar'},
        ),
        migrations.AlterField(
            model_name='peserta',
            name='wilayah',
            field=models.CharField(choices=[('SULSEL', 'SULSEL'), ('SULBAR', 'SULBAR'), ('SULTENG', 'SULTENG'), ('SULTRA', 'SULTRA'), ('SULUT', 'SULUT'), ('GORONTALO', 'GORONTALO')], max_length=10),
        ),
    ]
