# Generated by Django 2.2 on 2019-05-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0005_auto_20190510_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peserta',
            name='foto',
            field=models.ImageField(blank=True, upload_to='foto/'),
        ),
    ]
