# Generated by Django 2.2 on 2019-05-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0006_auto_20190510_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peserta',
            options={'ordering': ['nama'], 'verbose_name': 'Peserta Seminar', 'verbose_name_plural': 'Peserta Seminar'},
        ),
    ]
