# Generated by Django 2.2 on 2019-05-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0007_auto_20190520_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peserta',
            name='arrivaldate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='arrivaltime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
