# Generated by Django 2.2 on 2019-06-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0009_auto_20190526_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peserta',
            name='foto',
            field=models.ImageField(blank=True, default='noimg.png', upload_to='foto/'),
        ),
    ]
