# Generated by Django 2.2 on 2019-06-01 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0010_auto_20190601_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peserta',
            name='arrivaldate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peserta',
            name='arrivaltime',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peserta',
            name='catatan',
            field=models.TextField(blank=True),
        ),
    ]
