# Generated by Django 2.2 on 2019-06-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0011_auto_20190601_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peserta',
            name='arrivaldate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='arrivaltime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
